# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-04-02 23:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Thread',
            fields=[
                ('id', models.CharField(max_length=500, primary_key=True, serialize=False)),
                ('date_created_utc', models.IntegerField(null=True)),
                ('subreddit', models.CharField(max_length=500, null=True)),
                ('subreddit_id', models.CharField(max_length=500, null=True)),
                ('reddit_url', models.CharField(max_length=500, null=True)),
                ('reddit_id', models.CharField(max_length=500, null=True)),
                ('branch_url', models.CharField(max_length=500, null=True)),
                ('tweet_id', models.CharField(max_length=500, null=True)),
                ('author', models.CharField(max_length=500, null=True)),
                ('author_flair_text', models.CharField(max_length=500, null=True)),
                ('title', models.CharField(max_length=500, null=True)),
                ('score', models.IntegerField(default=0)),
                ('num_comments', models.IntegerField(default=0)),
            ],
        ),
    ]
